version: '3.7'

services:
  database_master:
    image: mysql:8.0.31
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysqldata_master:/var/lib/mysql
      - ./master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=root
      - MYSQL_DATABASE=ecommerce
      - MYSQL_PASSWORD=admin
    networks:
      - ecommerce-network
  database_develop:
    image: mysql:8.0.31
    container_name: "database_develop"
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - 3307:3306
    volumes:
      - mysqldata_develop:/var/lib/mysql
      - ./slave.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=root
      - MYSQL_DATABASE=ecommerce
      - MYSQL_PASSWORD=admin
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    driver: bridge